# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#  vmImage: ubuntu-latest
pool:
  name: MeuAgentPool
  
variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- powershell: |
    $PSVersionTable
    Get-Module -ListAvailable | Where-Object { $_.Name -like "*Security*" }
  displayName: 'Diagnóstico do PowerShell'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
