# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './APITempoDIO/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: InstallAndRestore
  displayName: 'Instalar e Restaurar'
  jobs:
  - job: InstallRestoreJob
    steps:
    - task: UseDotNet@2
      displayName: "Install .Net SDK"
      inputs:
        packageType: 'sdk'
        version: '8.x'
    - script: dotnet restore $(solution)
      displayName: 'Restore Solution'

- stage: Build
  displayName: 'Construir Solução'
  dependsOn: InstallAndRestore # Depende do estágio InstallAndRestore
  jobs:
  - job: BuildJob
    steps:
    - script: dotnet build $(solution) --configuration $(buildConfiguration)
      displayName: 'Build Solution'